name: Build and publish testing artifacts

on:
  workflow_dispatch:
    inputs:
      APPEND_NAME:
        description: 'Optional part to append to version name. If it is provided, it must contain only [0-9A-Za-z-].'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_NAME: ${{github.event.repository.name}}-artifacts
    steps:
      - name: Input arguments 1
        run: echo "Using appendix '${{ inputs.APPEND_NAME }}'"
      - name: Input arguments 2
        run: echo "Using appendix '$inputs.APPEND_NAME'"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.2
          cache: npm
      - name: install dependencies
        run: npm i
      - run: echo "ARTIFACTS_NAME=$ARTIFACTS_NAME"
      - run: npm pkg get version
      - run: echo "NEW_VERSION=$(npm pkg get version)-$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo $ARTIFACTS_NAME
      - run: echo $NEW_VERSION
      - run: mkdir -p $ARTIFACTS_NAME
      - run: npm run vsce -- --out $ARTIFACTS_NAME --no-git-tag-version $NEW_VERSION
      - run: cd $ARTIFACTS_NAME
      - run: ls